import pyautogui

pyautogui.press('Win')
pyautogui.sleep(1)
pyautogui.write('Google Chrome', interval = 0.4)
pyautogui.press('Enter')
pyautogui.sleep(2)
pyautogui.hotkey('alt', 'd')
pyautogui.write('instagram.com')
pyautogui.sleep(1)
pyautogui.press('enter')
pyautogui.sleep(1)
pyautogui.press('tab')
pyautogui.sleep(1)
pyautogui.write('seu @')
pyautogui.sleep(1)
pyautogui.press('tab')
pyautogui.write('sua senha')
pyautogui.sleep(1)
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.click()
pyautogui.sleep(30)
pyautogui.hotkey('alt', 'f4')